name: Docker CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Login ti Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secret.DOCKERHUB_USERNAME}}
          password: ${{secret.DOCKERHUB_TOKEN}}
      
