name: Docker CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Login ti Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./web
          push: true
          tags: ivydocker9/web:latest
          
      
